"""CLI scaffold generator — produces a Click-based CLI from a ToolSpec."""

from __future__ import annotations

import textwrap
from pathlib import Path

from clias.specgen.schema import ToolSpec, CommandSpec, Capability


class CLIScaffold:
    """Generates a standalone Python CLI script from a ToolSpec."""

    def __init__(self, spec: ToolSpec) -> None:
        self.spec = spec

    def generate(self, output_path: Path) -> Path:
        """Write a complete, runnable CLI script to output_path."""
        code = self._build_code()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code)
        output_path.chmod(0o755)
        return output_path

    def _build_code(self) -> str:
        parts = [
            self._header(),
            self._imports(),
            self._spec_embed(),
            self._main_group(),
            self._ask_command(),
            self._capability_groups(),
            self._entrypoint(),
        ]
        return "\n\n".join(parts) + "\n"

    def _header(self) -> str:
        return f'''\
#!/usr/bin/env python3
"""Auto-generated CLI for {self.spec.name}.

{self.spec.description}

Generated by CLIaS — https://github.com/CLIaS
"""'''

    def _imports(self) -> str:
        return """\
import json
import subprocess
import sys

import click
from rich.console import Console
from rich.prompt import Confirm

try:
    from litellm import completion
except ImportError:
    completion = None

console = Console()"""

    def _spec_embed(self) -> str:
        spec_json = self.spec.model_dump_json(indent=2)
        return f"TOOL_SPEC = json.loads(r'''\n{spec_json}\n''')"

    def _main_group(self) -> str:
        return f'''\
@click.group()
@click.version_option(version="{self.spec.version}")
def cli():
    """{self.spec.name}: {self.spec.description}"""
    pass'''

    def _ask_command(self) -> str:
        auth_section = ""
        if self.spec.interaction_methods:
            auth_notes = []
            for im in self.spec.interaction_methods:
                if im.auth_env_var:
                    auth_notes.append(
                        f"    - {im.method}: set ${im.auth_env_var} ({im.auth_type or 'unknown auth'})"
                    )
                if im.base_url:
                    auth_notes.append(f"    - {im.method} endpoint: {im.base_url}")
            if auth_notes:
                auth_section = (
                    '\\n\\nAuthentication / API notes:\\n' + '\\n'.join(auth_notes)
                )

        return f'''\
@cli.command()
@click.argument("request", nargs=-1, required=True)
@click.option("--execute", "-x", is_flag=True, help="Execute the command immediately.")
@click.option("--dry-run", "-n", is_flag=True, help="Show the command without executing.")
@click.option("--model", "-m", default="gpt-4o", help="LLM model to use.")
def ask(request, execute, dry_run, model):
    """Describe what you want in natural language."""
    if completion is None:
        console.print("[red]litellm is required. Install with: pip install litellm[/red]")
        sys.exit(1)

    user_input = " ".join(request)
    cmds_summary = "\\n".join(
        f"  {{c['canonical']}} — {{c.get('description', '')}}"
        for c in TOOL_SPEC.get("commands", [])
    )

    prompt = (
        f"You are a CLI assistant for **{{TOOL_SPEC['name']}}**.\\n\\n"
        f"{{TOOL_SPEC.get('description', '')}}\\n\\n"
        f"Available commands:\\n{{cmds_summary}}\\n\\n"
        "{auth_section}"
        f"The user wants: \\"{{user_input}}\\"\\n\\n"
        "Return ONLY the exact shell command(s). One per line. No explanations."
    )

    resp = completion(
        model=model,
        messages=[{{"role": "user", "content": prompt}}],
        temperature=0.1,
        max_tokens=1024,
    )
    commands_text = resp.choices[0].message.content.strip()

    console.print("\\n[bold]Proposed command(s):[/bold]")
    console.print(f"  [cyan]{{commands_text}}[/cyan]\\n")

    if dry_run:
        return

    should_run = execute or Confirm.ask("Execute?", default=False)
    if should_run:
        for line in commands_text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            console.print(f"[dim]$ {{line}}[/dim]")
            result = subprocess.run(line, shell=True)
            if result.returncode != 0:
                console.print(f"[red]Command exited with code {{result.returncode}}[/red]")'''

    def _capability_groups(self) -> str:
        groups_by_cap: dict[str, list[CommandSpec]] = {}
        cmd_map = {c.canonical: c for c in self.spec.commands}

        for cap in self.spec.capabilities:
            groups_by_cap[cap.name] = [
                cmd_map[ref] for ref in cap.related_commands if ref in cmd_map
            ]

        ungrouped = []
        grouped_cmds = set()
        for cmds in groups_by_cap.values():
            for c in cmds:
                grouped_cmds.add(c.canonical)
        for c in self.spec.commands:
            if c.canonical not in grouped_cmds:
                ungrouped.append(c)

        parts = []
        for cap_name, cmds in groups_by_cap.items():
            safe_name = cap_name.replace("-", "_").replace(" ", "_").lower()
            parts.append(self._make_group(safe_name, cap_name, cmds))

        if ungrouped:
            parts.append(self._make_group("commands", "Misc commands", ungrouped))

        return "\n\n".join(parts)

    def _make_group(self, group_name: str, label: str, cmds: list[CommandSpec]) -> str:
        lines = [
            f"@cli.group()",
            f"def {group_name}():",
            f'    """{label}"""',
            f"    pass",
        ]
        for cmd in cmds:
            cmd_func = self._make_command(group_name, cmd)
            lines.append("")
            lines.append(cmd_func)
        return "\n".join(lines)

    def _make_command(self, group_name: str, cmd: CommandSpec) -> str:
        parts = cmd.canonical.split()
        cmd_name = parts[-1] if len(parts) > 1 else parts[0]
        safe_name = cmd_name.replace("-", "_").lower()

        lines = [f'@{group_name}.command(name="{cmd_name}")']

        for arg in cmd.arguments:
            arg_name = arg.name.replace("-", "_").lower()
            if arg.required:
                lines.append(f'@click.argument("{arg_name}")')
            else:
                lines.append(f'@click.argument("{arg_name}", default=None, required=False)')

        for flag in cmd.flags:
            flag_clean = flag.flag.lstrip("-")
            param = flag_clean.replace("-", "_").lower()
            if flag.takes_value:
                lines.append(
                    f'@click.option("{flag.flag}", default=None, help="{flag.description}")'
                )
            else:
                lines.append(
                    f'@click.option("{flag.flag}", is_flag=True, help="{flag.description}")'
                )

        param_list = []
        for arg in cmd.arguments:
            param_list.append(arg.name.replace("-", "_").lower())
        for flag in cmd.flags:
            param_list.append(flag.flag.lstrip("-").replace("-", "_").lower())

        sig = ", ".join(param_list)
        lines.append(f"def {safe_name}({sig}):")
        lines.append(f'    """{cmd.description}"""')
        lines.append(f'    parts = ["{cmd.canonical}"]')

        for arg in cmd.arguments:
            arg_var = arg.name.replace("-", "_").lower()
            lines.append(f"    if {arg_var} is not None:")
            lines.append(f"        parts.append(str({arg_var}))")

        for flag in cmd.flags:
            flag_var = flag.flag.lstrip("-").replace("-", "_").lower()
            if flag.takes_value:
                lines.append(f"    if {flag_var} is not None:")
                lines.append(f'        parts.append(f"{flag.flag} {{{flag_var}}}")')
            else:
                lines.append(f"    if {flag_var}:")
                lines.append(f'        parts.append("{flag.flag}")')

        lines.append('    full_cmd = " ".join(parts)')
        lines.append('    console.print(f"[dim]$ {full_cmd}[/dim]")')
        lines.append("    subprocess.run(full_cmd, shell=True)")

        return "\n".join(f"    {l}" if i > 0 and not l.startswith("@") and not l.startswith("def ") else l for i, l in enumerate(lines))

    def _entrypoint(self) -> str:
        return '''\
if __name__ == "__main__":
    cli()'''
